/**
 * Tormenta20 roll-flavor parser.
 *
 * Tormenta20 (system id "t20") is a Brazilian Portuguese D20 RPG. All roll
 * labels produced by the system are in pt-BR; the patterns below match the
 * strings generated by the Foundry VTT Tormenta20 system (vizael/Tormenta20).
 *
 * Flavor text format varies depending on the kind of roll:
 *   Skill check  – "<Perícia>" or "Teste de <Perícia>" or "<Perícia> (<Atrib>)"
 *   Saving throw – "<Resistência>" or "Resistência de <Resistência>"
 *   Attack       – "Ataque" or "Ataque com <Arma>" or "<Arma> - Ataque"
 *   Spell attack – "Ataque Mágico" or "Ataque com Magia"
 *   Damage       – (not intercepted — let them appear in chat)
 *   Initiative   – "Iniciativa"
 *   Ability      – "Teste de <Atributo>" or "<Atributo>"
 */

// ── Tormenta20 vocabulary ─────────────────────────────────────────────────────

/** The three resistências (saving throws) */
const SAVES = ["Fortitude", "Reflexo", "Vontade"] as const;
type Save = (typeof SAVES)[number];

/** All Tormenta20 perícias (skills), including their common short forms */
const SKILLS: readonly string[] = [
    "Acrobacia",
    "Atletismo",
    "Cavalgar",
    "Conhecimento",
    "Cura",
    "Diplomacia",
    "Enganação",
    "Furtividade",
    "Guerra",
    "Iniciativa",
    "Intimidação",
    "Intuição",
    "Jogatina",
    "Ladinagem",
    "Luta",
    "Misticismo",
    "Nobreza",
    "Ocultismo",
    "Ofício",
    "Percepção",
    "Pilotagem",
    "Pontaria",
    "Religião",
    "Sobrevivência",
    "Vontade",
];

/** Tormenta20 atributos (ability scores) with their pt-BR names */
const ABILITIES: readonly string[] = [
    "Força",
    "Destreza",
    "Constituição",
    "Inteligência",
    "Sabedoria",
    "Carisma",
];

// Precompiled regular expressions ─────────────────────────────────────────────

/** "Iniciativa" anywhere in the flavor */
const RE_INITIATIVE = /iniciativa/i;

/** "Ataque" with an optional following weapon name, e.g. "Ataque com Espada Longa" */
const RE_ATTACK = /ataque(?:\s+(?:com|à\s+distância\s+com|mágico))?\s*(.*)?/i;

/** "<Weapon> - Ataque" format (weapon name before the dash) */
const RE_ATTACK_WEAPON_FIRST = /^(.+?)\s*[-–]\s*ataque/i;

/** "Resistência de <Save>" or just "<Save>" as the whole flavor */
const RE_SAVE_PREFIX = /resistência\s+de\s+(fortitude|reflexo|vontade)/i;

/** "Teste de <Something>" — covers both skill and ability checks */
const RE_SKILL_TESTE = /teste\s+de\s+(.+)/i;

/** "<Skill> (<Ability>)" — parenthesised ability abbreviation */
const RE_SKILL_PAREN = /^([^(]+?)\s*\([^)]+\)\s*$/i;

/** Matches "(dano)" anywhere — we deliberately skip damage rolls */
const RE_DAMAGE = /dano/i;

/** Matches "magia" or "mágico" — spell-related rolls */
const RE_SPELL = /mágico|magia/i;

// ── Build lookup sets for O(1) membership checks ──────────────────────────────

const SKILL_SET = new Set(SKILLS.map((s) => s.toLowerCase()));
const ABILITY_SET = new Set(ABILITIES.map((a) => a.toLowerCase()));
const SAVE_SET = new Set(SAVES.map((s) => s.toLowerCase()));

// ── Parser ────────────────────────────────────────────────────────────────────

/**
 * Parse a Tormenta20 chat-message flavor string into RollMeta.
 * Returns null when the flavor does not correspond to a roll type that should
 * be intercepted by the T20 overlay (e.g. plain damage rolls).
 */
export function parseT20(input: { flavor?: string; html?: JQuery }): RollMeta | null {
    const raw = input.flavor?.trim();
    if (!raw) return null;

    // Strip any HTML tags the system may embed in the flavor
    const flavor = stripHtml(raw);
    if (!flavor) return null;

    // Damage rolls — always pass through to normal chat
    if (RE_DAMAGE.test(flavor)) return null;

    // ── Initiative ────────────────────────────────────────────────────────────
    if (RE_INITIATIVE.test(flavor)) {
        return { category: "Iniciativa" };
    }

    // ── Saving throws (resistências) ──────────────────────────────────────────
    // "Resistência de Fortitude / Reflexo / Vontade"
    const savePrefix = RE_SAVE_PREFIX.exec(flavor);
    if (savePrefix) {
        const save = capitalise(savePrefix[1]);
        return { category: `Resistência de ${save}`, subcategory: save };
    }

    // Plain save name used as the whole flavor: "Fortitude", "Reflexo", "Vontade"
    if (SAVE_SET.has(flavor.toLowerCase())) {
        const save = capitalise(flavor) as Save;
        return { category: `Resistência de ${save}`, subcategory: save };
    }

    // ── Attack rolls (ataques) ────────────────────────────────────────────────
    // "Espada Longa - Ataque" (weapon-first format)
    const weaponFirst = RE_ATTACK_WEAPON_FIRST.exec(flavor);
    if (weaponFirst) {
        const weapon = weaponFirst[1].trim();
        return {
            category: "Ataque",
            subcategory: weapon || undefined,
        };
    }

    // "Ataque com Espada Longa" / "Ataque Mágico" / bare "Ataque"
    const attackMatch = RE_ATTACK.exec(flavor);
    if (attackMatch) {
        const rest = attackMatch[1]?.trim();
        if (RE_SPELL.test(flavor)) {
            return { category: "Ataque Mágico", subcategory: rest || undefined };
        }
        return { category: "Ataque", subcategory: rest || undefined };
    }

    // ── "Teste de …" — skill checks and ability checks ────────────────────────
    const testeMatch = RE_SKILL_TESTE.exec(flavor);
    if (testeMatch) {
        const subject = testeMatch[1].trim();
        return buildCheckMeta(subject);
    }

    // ── "<Perícia> (<Atributo>)" — parenthesised ability abbreviation ─────────
    const parenMatch = RE_SKILL_PAREN.exec(flavor);
    if (parenMatch) {
        const skill = parenMatch[1].trim();
        return buildCheckMeta(skill);
    }

    // ── Bare skill or ability name ────────────────────────────────────────────
    const lower = flavor.toLowerCase();
    if (SKILL_SET.has(lower)) {
        const skill = SKILLS.find((s) => s.toLowerCase() === lower) ?? flavor;
        return { category: `Teste de ${skill}`, subcategory: skill };
    }

    if (ABILITY_SET.has(lower)) {
        const ability = ABILITIES.find((a) => a.toLowerCase() === lower) ?? flavor;
        return { category: `Teste de ${ability}`, subcategory: ability };
    }

    // ── Fallback: unknown roll type — let it through as a generic d20 roll ────
    return null;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Build RollMeta for a check (skill or ability), given the raw subject text. */
function buildCheckMeta(subject: string): RollMeta {
    // Strip trailing "(Destreza)" abbreviation if present
    const clean = subject.replace(/\s*\([^)]*\)\s*$/, "").trim();

    // Recognise saves embedded in the text (e.g. "Teste de Fortitude")
    if (SAVE_SET.has(clean.toLowerCase())) {
        const save = capitalise(clean);
        return { category: `Resistência de ${save}`, subcategory: save };
    }

    return { category: `Teste de ${clean}`, subcategory: clean };
}

/** Remove HTML tags from a string (Foundry sometimes embeds them in flavor). */
function stripHtml(html: string): string {
    return html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
}

/** Capitalise the first letter of each word. */
function capitalise(str: string): string {
    return str
        .split(" ")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join(" ");
}
